stages:
- lint
- test
- deploy
language: node_js
node_js: '10'
cache:
  directories:
  - "~/.npm"
  - node_modules
notifications:
  email: false
git:
  submodules: false
before_install:
- "git config --global user.name \"\U0001F916\""
jobs:
  include:
  - stage: lint
    script: yarn lint
    skip_cleanup: true
  - stage: deploy
    if: branch = master
    before_deploy:
    - yarn add now --no-save
    - now rm demo --token $NOW_TOKEN --yes || true
    - yarn build
    deploy:
      provider: script
      script:
      - yarn travis-deploy-once "yarn semantic-release"
      - now demo --public --token $NOW_TOKEN -A ./now.json
      skip_cleanup: true
    after_deploy:
    - yarn deploy:gh
env:
  global:
  - secure: hvcX+opD+/HBTLvF7vG2eXrQUpEqRb3pgHtomo0UwNYxItYt+xIXhtK070CSd22UYhKJepS96biO5eIMtB6Qc3kju+qR62gXJeAs2iDTNs0QVGUHcvCrOckE8wUT2wMkObbj7KXYwx1iKvD6nCHjeM5Q/tb78L4pM+GGVtUq2MbncOk/3nxznt0Jjo83GHH73QxfGkKCl/V60G09VxnQhmYKBlj313386DVIiFVJBO6voLCto69DadAL1HdgkCSNrhiomBJGfz+Bh00VUFymbFCndy5impnNjiNezSjD2frDe5rIARrmyiQMPBDw5M701gMILbfieCSVsJ5Jxly8uEQqgUw4FZvvLmmHf3vc2KUavjTD5Z1E1RTnL9Wk2YtHhu7KIEkXT9eZaM+R/SHLwOny/hycIicKUjeQOdQqNVLtEMyarqrNWBgrs/6DzgS5zi3mPmuw8ZCa96aoYnXIb7aAMikre6iTzs+5PQOt4FjwE0Cx/DxrJvOs+8GDRCNpkYogIzIRa69iOrozBM+8+5IamF6GiWO7E0+A1CqL6vwunk97z48TcaUy9NPUEet7A4qyqj90/wglemqn4BDTo+CO02P3t4bR9tjq+vccTPvf+m6wzrV0Li/gtfMnGxsJYWrlf5TY8yknbgVWNfQDzqmMdwuhQiCzSE3Rr0rqOf8=
  - secure: f8LvorzUbesbsKDPiof5Bl7lZZShf7mO/mnlwK6d5yp+n07JCMGFZ8zSTX7vt2fv/0LhR9PVbONF7SvrypUvPKTSY5w2Pu8Kiow6FICZBfiG/2p+xZRrX8wa/RvFCZNk7zeyyV+p8tdsmmUqRg4qn97+l3o4vVoew4g4E5CusoOygt1bALqZ/uo7srMz1Tpur2VVrwTDQpwtHrmQ5AsuW2QuPSIX7dAdPR/hWYMjSImUVYM3jC60VdDBA1eeX2Rp17IyKWQil/l+5c60tElFnQV4bND0GWaN0bxuVmxbXY9cAeMxtxa94g0xKolNeWTJ3r0iBiTOoK0Gc8jFsIE342qbWp8rM69VTvMB7/fqzF3D/iUYG0f6AyiOzcgn7cZA1ht2EYxC8+1Qjc/pE4j632hGk9V/GrGiTl+pRjH3MMdH8Oqhv/U0esskIrLEljgxobhf5h7k3GOkO6xv/n4vTVEQ77NVdhLaSGSjonsgKQSqCQDp+pKNpk3WPfSVWzxj1/vLoWeMicWcgiEMNqcp//0oKUKZmZdwAxNRu/xvC+VcLd9eWJsh1dqFBW+UiltQTuZqmgzxysacD5mGGW3sWtm0rExO6uXl8c7fx0I/MzZiRRAfuw8xDf62uN+I/JEi17JTwhPZaNnWy9wh81AVr4614C8q//7/cpmixsNl3fc=
  - secure: jZKe08bfg3sDXRPurvWPOvmABETQbt/cJDBd/lzi13EXRkjYHGdMeDdA2wb8K5EiVoFLWgsgtXl/mB2a5ECaXEsVlttLZ9GnB3YpuchxbJbuVtoV/8Ol/IhzOxlvKRFwF0EdkoOgCfEbDO2T4XHsXNPEbBpEVMxsdytBM2YF7E9/OmyIKbaWo/hWXC5RbbyjsidmWmGGYYAgFK1cL9aoljvfO098xwBdmhlSEC1E9LtShN/8BwIFayNgBOjtiiyq/WGTsci025JeJU6cMFCyqfsCuS1L1kpir+zYHvFsSW+C3zIpGe7xxR239a+KJF++DK423dd1id94Pz9iaeCI384FlZZzzlkjwn96O5Yv+pfa57ULW3Rpwph1mUtDFbuwzULsE8EnA1ev1WCeRDkSmcWjK7Rx/rofvVWB3c7mIk/b+CqtuMVTkS5qjaVBcn/tegGij048H1WiziM8bxcMoTNeMEpTXSFQsMGUzeLs7FolOCvgXQNNG0FnLxVgGsfFCtV4TDsbTzbUMAOjD1uJbyFPiqN6knL1ACzVK1hMfIMWO+2wdywSYyS90+N9MNwqssYPEXpJ+qcLyEffyFItAcom8Y4VcVSeQ3OIH4bq+rLaGdtaRQMYCcJR5G0R7B/HOb4x/aMdM8SyZDKyXOCLsaemzR/XYMUJTo7Ccc+sONY=
